### ISSUE TITLE
reenable travis spellchecker

### ISSUE THREAD

**Issue by stdweird** [quattor/quattor.github.com#229]
currently fails with, disabled in https://github.com/quattor/quattor.github.com/pull/224/commits/62f1df43fb3be04aa1b3950c0cf51837386c3af8
```
[DEFAULT]

file_state = prevscore.json

check_state = false

directory_source = _posts

personal_word_list = dict.txt

log_to_file = false

log_debug = false

spelling_language = en_GB

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/enchant/tokenize/__init__.py", line 386, in next

    (word,pos) = next(self._curtok)

  File "/usr/lib/python3/dist-packages/enchant/tokenize/__init__.py", line 130, in __next__

    return self.next()

  File "/usr/lib/python3/dist-packages/enchant/tokenize/__init__.py", line 214, in next

    raise StopIteration()

StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/enchant/tokenize/__init__.py", line 386, in next

    (word,pos) = next(self._curtok)

  File "/usr/lib/python3/dist-packages/enchant/tokenize/__init__.py", line 130, in __next__

    return self.next()

  File "/usr/lib/python3/dist-packages/enchant/tokenize/__init__.py", line 214, in next

    raise StopIteration()

StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/enchant/tokenize/__init__.py", line 386, in next

    (word,pos) = next(self._curtok)

  File "/usr/lib/python3/dist-packages/enchant/tokenize/__init__.py", line 130, in __next__

    return self.next()

  File "/usr/lib/python3/dist-packages/enchant/tokenize/__init__.py", line 214, in next

    raise StopIteration()

StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "markdown-spellchecker-1.2/src/spellchecker.py", line 141, in <module>

    main()

  File "markdown-spellchecker-1.2/src/spellchecker.py", line 128, in main

    errortotal = mspell.checkfilelist(args.paths)

  File "/home/travis/build/quattor/quattor.github.com/markdown-spellchecker-1.2/src/markspelling.py", line 89, in checkfilelist

    self.errortotal += self.checkfile(filename)

  File "/home/travis/build/quattor/quattor.github.com/markdown-spellchecker-1.2/src/markspelling.py", line 83, in checkfile

    fileerrors = self.checklinelist(lines, filename)

  File "/home/travis/build/quattor/quattor.github.com/markdown-spellchecker-1.2/src/markspelling.py", line 74, in checklinelist

    (lineerrors, incodeblock) = self.checkline(line, linenumber, filename, incodeblock)

  File "/home/travis/build/quattor/quattor.github.com/markdown-spellchecker-1.2/src/markspelling.py", line 54, in checkline

    for err in self.spellcheck:

  File "/usr/lib/python3/dist-packages/enchant/checker/__init__.py", line 229, in __next__

    return self.next()

  File "/usr/lib/python3/dist-packages/enchant/checker/__init__.py", line 250, in next

    (word,pos) = next(self._tokens)

  File "/usr/lib/python3/dist-packages/enchant/tokenize/__init__.py", line 380, in __next__

    return self.next()

  File "/usr/lib/python3/dist-packages/enchant/tokenize/__init__.py", line 389, in next

    (word,pos) = next(self._tokenizer)

  File "/usr/lib/python3/dist-packages/enchant/tokenize/__init__.py", line 380, in __next__

    return self.next()

  File "/usr/lib/python3/dist-packages/enchant/tokenize/__init__.py", line 389, in next

    (word,pos) = next(self._tokenizer)

  File "/usr/lib/python3/dist-packages/enchant/tokenize/__init__.py", line 380, in __next__

    return self.next()

  File "/usr/lib/python3/dist-packages/enchant/tokenize/__init__.py", line 390, in next

    while self._skip(word):

  File "/usr/lib/python3/dist-packages/enchant/tokenize/__init__.py", line 428, in _skip

    if self._pattern.match(word):

TypeError: can't use a string pattern on a bytes-like object

The command "./.travis-scripts/spellchecker" exited with 1.

61.38s$ ./.travis-scripts/html-proofer
```

**Comment by jrha** [comment]
Caused by changes to travis environment, see #230 for fix.
